export const Films = [
    {id: 1, img: "assets/images/titanic.jpg",
    title: "Titanic", year: "1997",  nation:"USA",
    info: "Titanic is a 1997 American disaster film directed, written, produced, and co-edited by James Cameron. Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of RMS Titanic in 1912. Kate Winslet and Leonardo DiCaprio star as members of different social classes who fall in love during the ship's maiden voyage. The film also features Billy Zane, Kathy Bates, Frances Fisher, Gloria Stuart, Bernard Hill, Jonathan Hyde, Victor Garber, David Warner, Suzy Amis and Bill Paxton."},
    
    {id: 2, img: "assets/images/batman.jpg",
    title: "Batman", year: "2022",  nation:"USA",
    info: "The Batman is a 2022 American superhero film based on the DC Comics character Batman. Produced by Warner Bros. Pictures, DC Films, 6th & Idaho, and Dylan Clark Productions, and distributed by Warner Bros. Pictures, it is a reboot of the Batman film franchise. The film was directed by Matt Reeves, who wrote the screenplay with Peter Craig. It stars Robert Pattinson as Bruce Wayne / Batman alongside Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Peter Sarsgaard, Andy Serkis, and Colin Farrell. The film sees Batman, who has been fighting crime in Gotham City for two years, uncover corruption while pursuing the Riddler (Dano), a serial killer who targets Gotham's corrupt elite."},

    {id: 3, img: "assets/images/avengers.avif",
    title: "Avengers: End Game", year: "2019",  nation:"USA", 
    info: "Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse Thanos's actions in Infinity War."},

    {id: 4, img: "assets/images/batlle.jpg",
     title: "Battle thrown heaven", year: "2022",  nation:"China", 
     info: "Battle Through the Heavens (Chinese: 斗破苍穹; pinyin: Dòupò Cāngqióng; lit. 'Fight Through The Sky') is a 2018 Chinese television series adapted from the eponymous novel Doupo Cangqiong (斗破苍穹) by Tiancan Tudou (天蚕土豆). It stars Leo Wu, Lin Yun, Baron Chen, Li Qin, Xin Zhilei and Liu Meitong.[1] The series aired on Hunan TV on September 3, 2018 till October 25, 2018."},

    {id: 5, img: "assets/images/dragon.webp",
     title: "How to train your dragon", year: "2019",  nation:"USA", 
     info: "How to Train Your Dragon: The Hidden World (also known as How to Train Your Dragon 3) is a 2019 American computer-animated action fantasy film loosely based on the book series by Cressida Cowell. Produced by DreamWorks Animation and distributed by Universal Pictures, it is the sequel to How to Train Your Dragon 2 (2014) and the third and final installment of the How to Train Your Dragon trilogy.[4] Written and directed by Dean DeBlois and produced by Bonnie Arnold and Brad Lewis, the film stars the voices of Jay Baruchel, America Ferrera, Cate Blanchett, Craig Ferguson, and F. Murray Abraham. The film follows Hiccup as he seeks a dragon utopia known as the Hidden World while coming to terms with Toothless' new bond with a female Fury, as they deal with the threat of a ruthless dragon hunter named Grimmel the Grisly."},

    {id: 6, img: "assets/images/fast and furious.jpg", 
    title: "Fast and furious", year: "2023",  nation:"USA", 
    info: "Fast X (also known as Fast & Furious 10) is a 2023 American action film directed by Louis Leterrier from a screenplay written by Dan Mazeau and Justin Lin, both of whom also co-wrote the story with Zach Dean. It is the sequel to F9 (2021), the tenth main installment, and the eleventh installment overall in the Fast & Furious franchise. It stars Vin Diesel as Dominic Toretto alongside an ensemble cast including Michelle Rodriguez, Tyrese Gibson, Chris Ludacris Bridges, John Cena, Nathalie Emmanuel, Jordana Brewster, Sung Kang, Scott Eastwood, Daniela Melchior, Alan Ritchson, Helen Mirren, Brie Larson, Rita Moreno, Jason Statham, Jason Momoa, and Charlize Theron. In the film, Toretto must protect his family from Dante Reyes (Momoa), who seeks revenge for his father's death and the loss of his family's fortune."},

    {id: 7, img: "assets/images/rush hour.webp",
     title: "Rush hour", year: "2007",  nation:"USA", 
     info: "Rush Hour 3 is a 2007 American buddy action comedy film directed by Brett Ratner, written by Jeff Nathanson, and starring Jackie Chan, Chris Tucker, Max von Sydow, Hiroyuki Sanada, Noémie Lenoir, Yvan Attal and Youki Kudoh. It is the third installment in the Rush Hour franchise and centers on Inspector Lee (Chan) and Officer Carter (Tucker) tracking an assassin to Paris to unravel a mystery about the Chinese triads. Announced on May 7, 2006, filming began on July 4 on location in Paris and Los Angeles. Released on August 10, 2007, the film received negative reviews and grossed $258.1 million worldwide against a $140 million budget."},

    {id: 8, img: "assets/images/spiderman.jpg",
    title: "Spiderman", year: "2021",  nation:"USA", 
    info: "Spider-Man: No Way Home is a 2021 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios, and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and Spider-Man: Far From Home (2019), and the 27th film in the Marvel Cinematic Universe (MCU). The film was directed by Jon Watts and written by Chris McKenna and Erik Sommers. It stars Tom Holland as Peter Parker / Spider-Man alongside Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori, Marisa Tomei, Andrew Garfield, and Tobey Maguire. In the film, Parker asks Dr. Stephen Strange (Cumberbatch) to use magic to make his identity as Spider-Man a secret again following its public revelation at the end of Far From Home. When the spell is corrupted because of Parker's actions, the multiverse is broken open, which allows visitors from alternate realities to enter Parker's universe."},

    {id: 9, img: "assets/images/walking dead.jpg",
    title: "The Walking dead", year: "2013",  nation:"USA", 
    info: "The Walking Dead is an American post-apocalyptic horror drama television series based on the comic book series of the same name by Robert Kirkman, Tony Moore, and Charlie Adlard—together forming the core of The Walking Dead franchise. The series features a large ensemble cast as survivors of a zombie apocalypse trying to stay alive under near-constant threat of attacks from zombies chiefly known as walkers by the other characters. With the collapse of modern civilization, these survivors must confront other human survivors who have formed groups and communities with their own sets of laws and morals, sometimes leading to open, hostile conflict between them. The series is the first television series within The Walking Dead franchise."},

];